// Актуальный каталог Sale + обложки (webp из TG assets).
// Подключается до app.js; карточки рисует markup() на клиенте.
window.KIRA_PRODUCTS = [
  {
    id: "konsult_psiholog",
    title: "Консультация психолога",
    price: "6 000 ₽",
    url: "https://tvoi-shag.online/konsult_psiholog",
    match: ["/konsult_psiholog"],
    image: "/products/psy_once.webp",
  },
  {
    id: "konsult_psihiatr",
    title: "Консультация психиатра",
    price: "8 400 ₽",
    url: "https://tvoi-shag.online/konsult_psihiatr",
    match: ["/konsult_psihiatr"],
    image: "/products/med_once.webp",
  },
  {
    id: "konsult_psiholog_family",
    title: "Семейная консультация психолога",
    price: "15 000 ₽",
    url: "https://tvoi-shag.online/konsult_psiholog_family",
    match: ["/konsult_psiholog_family"],
    image: "/products/family_once.webp",
  },
  {
    id: "konsult_shurov",
    title: "Консультация с доктором Шуровым",
    price: "60 000 ₽",
    url: "https://tvoi-shag.online/konsult_shurov",
    match: ["/konsult_shurov"],
    image: "/products/shurov_once.webp",
  },
  {
    id: "vip_terapia_8",
    title: "VIP сопровождение психиатра (8 сессий)",
    price: "113 990 ₽",
    url: "https://tvoi-shag.online/vip_terapia",
    match: ["/vip_terapia"],
    exclude: ["/vip_terapia_4session"],
    image: "/products/vip_med.webp",
  },
  {
    id: "vip_terapia_4",
    title: "VIP сопровождение психиатра (4 сессии)",
    price: "65 990 ₽",
    url: "https://tvoi-shag.online/vip_terapia_4session",
    match: ["/vip_terapia_4session"],
    image: "/products/vip_med.webp",
  },
  {
    id: "vip_zavisim_8",
    title: "VIP сопровождение зависимых (8 сессий)",
    price: "113 990 ₽",
    url: "https://tvoi-shag.online/vip_zavisim",
    match: ["/vip_zavisim"],
    exclude: ["/vip_zavisim_4session"],
    image: "/products/vip_addiction.webp",
  },
  {
    id: "vip_zavisim_4",
    title: "VIP сопровождение зависимых (4 сессии)",
    price: "65 990 ₽",
    url: "https://tvoi-shag.online/vip_zavisim_4session",
    match: ["/vip_zavisim_4session"],
    image: "/products/vip_addiction.webp",
  },
  {
    id: "vip_sozavisim_8",
    title: "VIP сопровождение созависимых (8 сессий)",
    price: "113 990 ₽",
    url: "https://tvoi-shag.online/vip_sozavisim",
    match: ["/vip_sozavisim"],
    exclude: ["/vip_sozavisim_4session"],
    image: "/products/vip_codependency.webp",
  },
  {
    id: "vip_sozavisim_4",
    title: "VIP сопровождение созависимых (4 сессии)",
    price: "65 990 ₽",
    url: "https://tvoi-shag.online/vip_sozavisim_4session",
    match: ["/vip_sozavisim_4session"],
    image: "/products/vip_codependency.webp",
  },
  {
    id: "kurs_zavisimyh",
    title: "Курс для зависимых",
    price: "53 990 ₽",
    url: "https://shurovhelp.com",
    matchHost: ["shurovhelp.com", "www.shurovhelp.com"],
    image: null,
  },
  {
    id: "video_zavisimyh",
    title: "Видеокурс для зависимых",
    price: "9 900 ₽",
    url: "https://shurovsos.ru",
    matchHost: ["shurovsos.ru", "www.shurovsos.ru"],
    image: null,
  },
  {
    id: "video_sozavisimyh",
    title: "Видеокурс для созависимых",
    price: "9 900 ₽",
    url: "https://tvoi-shag.online/perviyshag_12",
    match: ["/perviyshag_12"],
    image: null,
  },
  {
    id: "video_trevoga",
    title: "Видеокурс по тревоге",
    price: "9 900 ₽",
    url: "https://school.shurovhelp.ru/panic_lending",
    match: ["/panic_lending"],
    matchHost: ["school.shurovhelp.ru"],
    image: null,
  },
  {
    id: "catalog_all",
    title: "Все направления школы",
    price: "",
    url: "https://tvoi-shag.online/perviyshag_all",
    match: ["/perviyshag_all"],
    image: "/products/catalog.webp",
  },
];
